services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: primeflux_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: primeflux_db
      POSTGRES_USER: primeflux_user
      POSTGRES_PASSWORD: primeflux_password
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Docker/Django/dockerfile  # Patched path location
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE: postgres                    # Patched for entrypoint.sh
      DB_HOST: db                           # Patched for entrypoint.sh
      DB_PORT: 5432                         # Patched for entrypoint.sh
      PRIMEFLUX_DATABASE: '{"default":{"HOST":"db"}}'
      PRIMEFLUX_LOCAL_SETTINGS_PATH: /app/local/settings.prod.py  # Patched file & path mapping

volumes:
  db_data:
    driver: local
